BART:
  output_dir: "BART"
  evaluation_strategy: "epoch"
  metric_for_best_model: "eval_loss"
  learning_rate: 2e-5
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 16
  weight_decay: 0.01
  num_train_epochs: 5
  save_strategy: "no"
