BART:
  output_dir: "BART"
  evaluation_strategy: "epoch"
  metric_for_best_model: "eval_loss"
  learning_rate: 2e-5
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 128
  weight_decay: 0.01
  num_train_epochs: 5

Pegasus:
  output_dir: "Pegasus"
  evaluation_strategy: "epoch"
  metric_for_best_model: "eval_loss"
  learning_rate: 2e-5
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 128
  weight_decay: 0.01
  num_train_epochs: 5

