artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  hf_dataset_name: "Samsung/samsum"
  local_data_file: artifacts/data_ingestion/Dataset

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Dataset
  STATUS_FILE: artifacts/data_validation/status.txt
  
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Dataset
  filtered_data_path: artifacts/data_transformation/Dataset
  tokenizer1_name: facebook/bart-large-cnn
  tokenizer2_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data1_path: artifacts/data_transformation/tokenized_bart
  data2_path: artifacts/data_transformation/tokenized_pegasus
  model1_ckpt: facebook/bart-large-cnn
  model2_ckpt: google/pegasus-cnn_dailymail