artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  hf_dataset_name: "Samsung/samsum"
  local_data_file: artifacts/data_ingestion/Dataset

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Dataset
  STATUS_FILE: artifacts/data_validation/status.txt